param(
    [string]$BaseVersion = "1.2"
)

$ErrorActionPreference = "Stop"

function Get-NextVersion {
    param(
        [string]$VersionsDir,
        [string]$BaseVersion
    )

    $escaped = [regex]::Escape($BaseVersion)
    $maxPatch = 0

    if (Test-Path $VersionsDir) {
        Get-ChildItem -Path $VersionsDir -Directory | ForEach-Object {
            if ($_.Name -match "^$escaped\.(\d+)$") {
                $patch = [int]$Matches[1]
                if ($patch -gt $maxPatch) {
                    $maxPatch = $patch
                }
            }
        }
    }

    return "$BaseVersion.$($maxPatch + 1)"
}

function Get-FileVersion {
    param([string]$Version)

    $parts = $Version.Split(".")
    if ($parts.Count -eq 2) {
        return "$Version.0.0"
    }
    if ($parts.Count -eq 3) {
        return "$Version.0"
    }
    return $Version
}

function Invoke-Checked {
    param(
        [string]$FilePath,
        [string[]]$Arguments
    )

    & $FilePath @Arguments
    if ($LASTEXITCODE -ne 0) {
        throw "Command failed: $FilePath $($Arguments -join ' ')"
    }
}

$repoRoot = Split-Path -Parent $MyInvocation.MyCommand.Path
$versionsDir = Join-Path $repoRoot "versions"
$version = Get-NextVersion -VersionsDir $versionsDir -BaseVersion $BaseVersion
$fileVersion = Get-FileVersion -Version $version

$headerPath = Join-Path $repoRoot "firmware\leonardo-wheel\BuildVersion.h"
$previousHeader = if (Test-Path $headerPath) { Get-Content -Path $headerPath -Raw } else { $null }
$stagingDir = Join-Path $env:TEMP ("ffbwheel-release-" + $version)
$publishDir = Join-Path $stagingDir "app"
$firmwareOutDir = Join-Path $stagingDir "firmware"
$releaseDir = Join-Path $versionsDir $version
$success = $false

New-Item -ItemType Directory -Force -Path $versionsDir | Out-Null
if (Test-Path $stagingDir) {
    Remove-Item -Path $stagingDir -Recurse -Force
}
New-Item -ItemType Directory -Force -Path $publishDir, $firmwareOutDir | Out-Null

$headerContents = @(
    "#pragma once",
    "",
    "/* Auto-generated by build_versioned_release.ps1 during release packaging. */",
    "#define FW_VERSION `"$version`""
) -join "`r`n"

try {
    Set-Content -Path $headerPath -Value $headerContents -Encoding Ascii

    Invoke-Checked -FilePath "cmd.exe" -Arguments @(
        "/c",
        (Join-Path $repoRoot "firmware\leonardo-wheel\build_firmware.bat")
    )

    Invoke-Checked -FilePath "dotnet" -Arguments @(
        "publish",
        (Join-Path $repoRoot "desktop-app\FFBWheelConfig.csproj"),
        "-c", "Release",
        "-r", "win-x64",
        "--self-contained", "false",
        "-p:PublishSingleFile=true",
        "-p:IncludeNativeLibrariesForSelfExtract=true",
        "-p:DebugSymbols=false",
        "-p:DebugType=None",
        "-p:Version=$version",
        "-p:FileVersion=$fileVersion",
        "-p:AssemblyVersion=$fileVersion",
        "-p:InformationalVersion=$version",
        "-o", $publishDir
    )

    $firmwareBuildDir = Join-Path $repoRoot "firmware\leonardo-wheel\build"
    $hexFiles = Get-ChildItem -Path $firmwareBuildDir -Filter "*.hex"
    if (-not $hexFiles) {
        throw "No firmware .hex files were produced in $firmwareBuildDir"
    }

    if (Test-Path $releaseDir) {
        Remove-Item -Path $releaseDir -Recurse -Force
    }

    $releaseAppDir = Join-Path $releaseDir "app"
    $releaseFirmwareDir = Join-Path $releaseDir "firmware"

    New-Item -ItemType Directory -Force -Path $releaseDir, $releaseAppDir, $releaseFirmwareDir | Out-Null
    Copy-Item -Path (Join-Path $publishDir "*") -Destination $releaseAppDir -Recurse -Force
    Copy-Item -Path $hexFiles.FullName -Destination $releaseFirmwareDir -Force

    $appExe = Get-ChildItem -Path $releaseAppDir -Filter "*.exe" |
        Where-Object { $_.Name -notmatch "^setup" } |
        Select-Object -First 1

    $metadata = [ordered]@{
        version = $version
        fileVersion = $fileVersion
        builtAt = (Get-Date).ToString("o")
        appExe = if ($appExe) { $appExe.Name } else { "" }
        firmwareFiles = (Get-ChildItem -Path $releaseFirmwareDir -Filter "*.hex" | Select-Object -ExpandProperty Name)
    } | ConvertTo-Json -Depth 3

    Set-Content -Path (Join-Path $releaseDir "build-info.json") -Value $metadata -Encoding Ascii
    Set-Content -Path (Join-Path $versionsDir "latest.txt") -Value $version -Encoding Ascii

    $success = $true

    Write-Host ""
    Write-Host "Created version $version"
    Write-Host "App output:      $((Join-Path $releaseDir 'app'))"
    Write-Host "Firmware output: $((Join-Path $releaseDir 'firmware'))"
    Write-Host ""
}
finally {
    if (-not $success) {
        if ($null -ne $previousHeader) {
            Set-Content -Path $headerPath -Value $previousHeader -Encoding Ascii
        } else {
            Remove-Item -Path $headerPath -Force -ErrorAction SilentlyContinue
        }
        Remove-Item -Path $releaseDir -Recurse -Force -ErrorAction SilentlyContinue
    }

    Remove-Item -Path $stagingDir -Recurse -Force -ErrorAction SilentlyContinue
}
